### PR TITLE
adding basic unit conversion in cdm parsing process

### PR DESCRIPTION
**Pull request by claytonpbarrows**
@KyraDiF this should address your angle limit violations... but there is another error that I haven't been able to address.

### CODE REVIEW

**Comment by claytonpbarrows** [comment]
Also interested in @daniel-thom take on this implementation

**Comment by daniel-thom** [comment]
👍

**Comment by KyraDiF** [comment]
@claytonpbarrows I'm still getting bus angle errors from the bus.csv data, which is in degrees. Should bus_csv_parser!I() also convert the bus angle to radians?

**Comment by claytonpbarrows** [comment]
This PR should make the conversion.

**Comment by KyraDiF** [comment]
@claytonpbarrows Dan figured out that your changes do the conversion once we specified that the unit is degrees in the user_descriptor yaml in the RTS_GMLC directory. He pushed that change to the improve-timeseries branch.

**Comment by claytonpbarrows** [comment]
Sorry, I forgot to push the data changes.

**Pull request merged**
